name: 'pnpm-node-setup'
description: 'Install pnpm, setup node with caching, and install dependencies.'
runs: 
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash 
