name: Continuous Integration Reusable Workflow
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Configure pnpm and Node
        uses: ./.github/actions/pnpm-node-setup
      - run: pnpm lint
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Configure pnpm and Node
        uses: ./.github/actions/pnpm-node-setup
      - run: pnpm test
  # cypress-run:
  #   runs-on: ubuntu-24.04
  #   needs: build
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v4
  #     - name: Configure pnpm and Node
  #       uses: ./.github/actions/pnpm-node-setup
  #     - name: Generate Prisma Client
  #       run: pnpx prisma generate
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         build: pnpm build
  #         start: pnpm start
  #         wait-on: 'http://localhost:3000'
