name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - name: Lint code
        run: pnpm lint
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs: [lint, vitest-run]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - run: pnpm build
      - name: Upload Next.js Build Artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: next-build
          path: .next
          if-no-files-found: error
  cypress-run:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - name: Download Next.js Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start
          wait-on: 'http://localhost:3000'
 