name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - name: Lint code
        run: pnpm lint
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - run: pnpm test
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
  build:
    runs-on: ubuntu-latest
    needs: [lint, vitest-run]
    steps:
      - name: Ci setup
        uses: ./.github/actions/ci-setup
      - run: pnpm build
 